export const PRODUCT_DETAILS_FETCH_REQUEST = "PRODUCT_DETAILS_FETCH_REQUEST";
export const PRODUCT_DETAILS_FETCH_SUCCESS = "PRODUCT_DETAILS_FETCH_SUCCESS";
export const PRODUCT_DETAILS_FETCH_FAIL = "PRODUCT_DETAILS_FETCH_FAIL";
